# Site settings
title: Testworx
header-img: img/home-bg.jpg
email: nick@testworx.io
copyright_name: Nick Oppersdorff
description: “A technical testing blog covering Selenium, Jmeter, test automation and performance testing.“
baseurl: ""
url: "http://www.testworx.io"
twitter_username: nickOppersdorff
github_username:  testWorx
email_username:  nick@testworx.io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
